const addonsSeed = [
  {
    name: 'Aeroporto / Heliporto',
    level: 1,
    description: 'Um heliporto para pequenos helicópteros.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 7,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 2,
    description: 'Um heliporto para helicópteros comerciais.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 11,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 3,
    description:
      'Um aeroporto para aeronaves monomotor e ultra-leves, com pista de terra.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 4,
    description:
      'Um aeroporto com pista de asfalto, suportando pequenos jatinhos, e turbo hélices de transporte de carga.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 22,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 5,
    description:
      'Um aeroporto de respeito, suportando aeronaves comerciais, talvez o maior da região.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 30,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 35,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 6,
    description:
      'Um aeroporto internacional, suportando grandes aeronaves, e de carga pesada.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 40,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 50,
    time_qty: 1,
    time_type: 'years',
  },
  {
    name: 'Animais Defensores',
    level: 1,
    description: '4 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 1,
    influence: 'Bureaucracy, Street',
    influence_qty: 1,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Animais Defensores',
    level: 2,
    description: '8 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 3,
    influence: 'Bureaucracy, Street',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Animais Defensores',
    level: 3,
    description: '12 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 6,
    influence: 'Bureaucracy, Street',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Animais Defensores',
    level: 4,
    description: '16 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 10,
    influence: 'Bureaucracy, Street',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Animais Defensores',
    level: 5,
    description: '32 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 12,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Animais Defensores',
    level: 6,
    description: '48 animais.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 20,
    influence: 'Bureaucracy, Street',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 1,
    description: '4 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 1,
    influence: 'Bureaucracy, Street',
    influence_qty: 1,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Animais Vigilantes',
    level: 2,
    description: '8 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 3,
    influence: 'Bureaucracy, Street',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Animais Vigilantes',
    level: 3,
    description: '12 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 6,
    influence: 'Bureaucracy, Street',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Animais Vigilantes',
    level: 4,
    description: '16 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 10,
    influence: 'Bureaucracy, Street',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 5,
    description: '32 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 12,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 6,
    description: '48 animais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 20,
    influence: 'Bureaucracy, Street',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 1,
    description:
      'Você conseguiu esconder pelo menos algumas armadilhas de corda que você tem.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 2,
    description:
      'Você diversificou os tipos de armadilhas, buracos com estacas, grades que caem, baldes de ácido, lanças e flechas que saem de buracos escondidos da parede, uma bola grande que rola por um corredor, e claro, todas ocultas.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 3,
    description:
      'Você conseguiu as mais letais armadilhas (pêndulos com lâminas afiadas, paredes com estacas que se fecham), e claro, colocou um dispositivo para rearmá-las.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 4,
    description:
      'Armas estacionárias, muros com estacas de madeira, lança-chamas, grandes quantidades de ácidos e placas de pressão, todos estão no seu arsenal agora.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 9,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 5,
    description:
      'Explosivos e gatilhos remotos foram instalados (você tem o controle remoto para ativar). Em conjunto com a Rede de Computadores você tem uma variada gama de maneiras de matar esperando por um invasor.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 21,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 6,
    description:
      'Abra o guia do mestre de D&D e veja a tabela de armadilhas, você pode escolher todas.',
    defense: true,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 28,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 1,
    description:
      'Armamentos que podem ser disparados em uma única direção controlado por uma pessoa.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x1',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 2,
    description:
      'Armamentos montados em uma base giratória mas que ainda devem ser disparados por alguém.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x2',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 3,
    description:
      'Controlado por um computador com um sistema básico de análise de ameaças.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 4,
    description:
      'Controlado por um computador com um sistema médio de análise de ameaças.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x4',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 9,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 5,
    description:
      'Controlado por um computador com um sistema de Inteligência Artificial Básico.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 21,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 6,
    description:
      'Controlado por um computador com um sistema de Inteligência Artificial Intermediário.',
    defense: true,
    surveillance: false,
    req_background: 'Resources x6',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 28,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Biblioteca',
    level: 1,
    description:
      'Uma pequena sala com uma coleção completa de enciclopédias, alguns clássicos e guias de referência.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 1,
    influence: 'University',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 2,
    description:
      'Algumas salas com um computador, livros de direitos, revistas, e uma coleção de publicações.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 2,
    influence: 'University',
    influence_qty: 8,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 3,
    description:
      'A grande coleção de livros, algumas peças genuínas de arte, e talvez uns dois manuscritos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 3,
    influence: 'University',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 4,
    description:
      'A biblioteca tem pelo menos uma obra-prima, algumas peças genuínas de arte, publicações de conhecimentos perdidos, e mais manuscritos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 4,
    influence: 'University',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 5,
    description:
      'Informações que levariam décadas para serem lidas. Uma inacreditável fonte de conhecimento, a biblioteca possui ao menos uma obra-prima de algum artista famoso e outras tantas obra-primas de artistas não tão conhecidos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 5,
    influence: 'University',
    influence_qty: 22,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 6,
    description:
      'A biblioteca possui manuscritos de autores famosos e uma gama de informações sobre todo o mundo afora.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 6,
    influence: 'University',
    influence_qty: 28,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 1,
    description: '2 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 2,
    influence: 'Health, Street, Underworld',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 2,
    description: '4 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 2,
    influence: 'Health, Street, Underworld',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 3,
    description: '8 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 3,
    influence: 'Health, Street, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 4,
    description: '16 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 3,
    influence: 'Health, Street, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 5,
    description: '24 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 4,
    influence: 'Health, Street, Underworld',
    influence_qty: 20,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 6,
    description: '36 humanos.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 5,
    influence: 'Health, Street, Underworld',
    influence_qty: 30,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 1,
    description:
      'Você possui um cofre pequeno, com uma senha numérica, escondido atrás de um quadro na parede. Nível de segurança equivalente a um cofre comercial.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 1,
    influence: 'Finance, Industry',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 2,
    description:
      'Você possui um cofre grande, a prova de fogo e com uma fechadura tetra além da senha numérica, no chão de seu escritório. Nível de segurança equivalente a um cofre industrial.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 2,
    influence: 'Finance, Industry',
    influence_qty: 4,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 3,
    description:
      'Seu cofre é uma sala com vários compartimentos, paredes, chão e teto reforçado com várias camadas de metal, hermeticamente fechado e a prova de fogo. O cofre só abre com identificação biométrica. Nível de segurança equivalente a um cofre de banco.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 5,
    influence: 'Finance, Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 4,
    description:
      'Você possui um cofre de dar inveja a qualquer banco, uma sala com vários sub cofres internos, todos muito bem protegidos, além das proteções usuais seu cofre ainda requer um reconhecimento por voz. Nível de segurança equivalente ao de um cofre de cassino.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 10,
    influence: 'Finance, Industry',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 5,
    description:
      'O Tesouro Nacional invejaria seu cofre se o visse. O seu cofre é um cofre dentro de um cofre, duas. É preciso duas chaves e o reconhecimento biométrico e de voz de duas pessoas diferentes, definidas pelos proprietários para abrí-lo. E isto só pode ser feito se ambos estiverem ao mesmo tempo. Nível de segurança equivalente ao de agências do Tesouro Nacional.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 15,
    influence: 'Finance, Industry',
    influence_qty: 20,
    time_qty: 4,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 6,
    description:
      'Se sua casa explodisse, certamente algo ainda estaria de pé e intacto. Nível de Segurança equivalente ao Tesouro Nacional da Suíça.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 25,
    influence: 'Finance, Industry',
    influence_qty: 30,
    time_qty: 8,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 1,
    description:
      'Inscrições mágicas, apitos sobrenaturais, ventos em locais fechados, avisam da presença de algumas criaturas sobrenaturais menores. Pode detectar um carniçal ou alguém com Fé Verdadeira.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x1',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 1,
    influence: 'Occult',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 2,
    description:
      'Quadros que viram os olhos para acompanhar alguém, plantas que murcham, ampulheta que faz a areia subir ao invés de cair, avisam da presença de algumas criaturas sobrenaturais intermediárias. Pode detectar espíritos e alguns fomores.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x2',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 2,
    influence: 'Occult',
    influence_qty: 10,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 3,
    description:
      'Portas que rangem, espelhos que refletem uma imagem distorcida, água que muda de cor, podem ser indícios de que alguma criatura sobrenatural maior está presente no Refúgio. Pode detectar vampiros, lobisomens, fadas. *Ou fantasmas, no caso de Refúgio de membros de clã com Necromancia.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x3',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 3,
    influence: 'Occult',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 4,
    description:
      'Torneiras que se abrem, aparelhos eletrônicos que se ligam sem razão alguma, vozes que ecoam em determinados cômodos avisam da presença de criaturas sobrenaturais superiores. Pode detectar vampiros ofuscados ou em projeção astral, lobisomens na umbra, fantasmas.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x4',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 4,
    influence: 'Occult',
    influence_qty: 30,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 5,
    description:
      'Portas que se fecham e se trancam, barulhos de pessoas correndo por toda parte, gritos estridentes, sangue que escorre da parede, avisam de presenças de criaturas poderosas no Refúgio. Pode detectar presença de demônios ou magos. Podendo inclusive avisar a distância. *Ou Demônios Sebau, no caso do Refúgio de membros clã Setita.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x5',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 5,
    influence: 'Occult',
    influence_qty: 35,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 6,
    description:
      'Estátuas que barram a entrada, paredes que falam, água que "caem" do chão para o teto, avisam da presença de criaturas desconhecidas, mas ainda sim, poderosas. Pode detectar a presença de uso de poderes sobrenaturais no local, de criaturas cujo o conhecimento já está muito esquecido, ou mesmo distúrbios que nada tem haver com criaturas, mas está presente no local.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x6',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 6,
    influence: 'Occult',
    influence_qty: 40,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 1,
    description: 'Agradável (Crafts x1).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Design Artístico',
    level: 2,
    description: 'Agradável (Crafts x2).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 7,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Design Artístico',
    level: 3,
    description: 'Impressionante (Crafts x3).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'month',
  },
  {
    name: 'Design Artístico',
    level: 4,
    description: 'Impressionante (Crafts x4).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 14,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 5,
    description: 'Majestoso (Crafts x5).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 19,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 6,
    description: 'Majestoso (Crafts x6).',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 25,
    time_qty: 1,
    time_type: 'years',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 1,
    description:
      'As paredes são de tijolos, as portas de metal, é necessário algum tempo e uma marreta para derrubar. Alguém com Potência x1 e algum tempo poderia derrubar esta parede fácil.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 2,
    description:
      'Alguém com Potência x2 levaria um bom tempo para derrubar esta parede.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 3,
    description:
      'Alguém com Potência x3 ou uma britadeira levaria algum tempo para romper esta parede.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 15,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 4,
    description:
      'Alguém com Potência x4 e algum tempo ou uma pequena quantidade de explosivos poderiam derrubar esta parede.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 20,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 5,
    description:
      'Alguém com Potência x5 e algum tempo ou uma média quantidade de explosivos poderiam derrubar esta parede.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 30,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 6,
    description:
      'As paredes apenas vibram em um grande terremoto. Materiais feitos para resistir a terremotos foram utilizados na construção destas paredes para prevenir que sejam derrubadas.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 40,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Labirinto',
    level: 1,
    description:
      'Dois corredores, se você pegar o da esquerda encontrará o caminho.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 2,
    description: 'Um único piso, mas um desafio menor.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 3,
    description:
      'Dois ou três pisos, ou algumas centenas de metros quadrados, um verdadeiro desafio.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 8,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 4,
    description:
      'Muitos pisos (4-6), ou alguns quilômetros quadrados, e muito complexo, algumas paredes escondem alavancas que abrem portas secretas. Uma vez vi um minotauro andando por aqui.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 12,
    time_qty: 4,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 5,
    description:
      'Complexo subterrâneo multifacetado. Algumas das paredes de posição automaticamente. Muitas vezes, alguns movimentos fazem o labirinto se fecham completamente, permitindo a saída apenas se conhecer alguma porta secreta.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warren Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 16,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 6,
    description:
      'O labirinto se estende para baixo, sumindo cada vez mais na escuridão. Os que ficam presos dentro dele, descem cada vez mais, a maioria nunca volta.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warren Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 24,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 1,
    description:
      'O laboratório possui ferramentas o suficiente para realizar algumas experiências básicas.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x1',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 1,
    influence: 'University',
    influence_qty: 3,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 2,
    description:
      'O laboratório possui recursos para realizar pesquisas novas e expandir o conhecimento em várias áreas. Mais de um cientista pode trabalhar ao mesmo tempo neste local.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x2',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 2,
    influence: 'University',
    influence_qty: 6,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 3,
    description:
      'O laboratório tem salas e equipamento para suportar vários cientistas e potencialmente grandes cientistas. Seus recursos podem produzir trabalhos originais e de grande influência.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 3,
    influence: 'University',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 4,
    description:
      'O laboratório tem equipamentos únicos para suportar uma figura significativa da área científica. Trabalhos verdadeiramente originais podem ser produzidos neste departamento. Este laboratório pode publicar regularmente teses científicas.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x4',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 4,
    influence: 'University',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 5,
    description:
      'Este laboratório pode competir com grandes laboratórios de pesquisa. Tudo que um laboratório precisa, ele tem. Ele pode produzir patentes o suficiente para ter seu mérito reconhecido mundialmente, mas isso não quer dizer que ele divulgue isso para o mundo mortal.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 5,
    influence: 'University',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 6,
    description:
      'Este laboratório é uma referência para seu campo de estudo. Boatos de seu trabalho correm pelos grandes círculos de seu campo de estudo.',
    defense: false,
    surveillance: false,
    req_background: 'Resources x6',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 6,
    influence: 'University',
    influence_qty: 18,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Oficina Mecânica',
    level: 1,
    description:
      'Uma oficina humilde, com um pequeno set de ferramentas, você pode trocar uma fechadura ou pregar algumas tábuas aqui.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 2,
    description:
      'Um conjunto respeitável de ferramenta, assim como uma mesa apropriada, você pode consertar equipamentos e/ou Add-ons de até nível 2.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry',
    influence_qty: 8,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 3,
    description:
      'Algumas ferramentas incomuns está presente no local, como serra tico-tico entre outras, pode consertar equipamentos de até nível 3.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 4,
    description:
      'Uma grande gama de ferramentas, algumas restrita a construção civil, pode se encontrar bombas de ar, britadeira, torqueadeira, tudo a disposição, pode se reparar equipamentos de até nível 4.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 8,
    influence: 'Bureaucracy, Industry',
    influence_qty: 16,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 5,
    description:
      'Tudo que precisa numa oficina tem ali, um escavadeira está estacionada no canto, cabos e vigas de aço no teto permite o transporte fácil de equipamento pesado, pode consertar equipamentos de até nível 5.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 12,
    influence: 'Bureaucracy, Industry',
    influence_qty: 20,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 6,
    description:
      'Você tem ferramentas modificadas para cada equipamento em seu refúgio. Pode arrumar qualquer coisa de nível 6 ou inferior.',
    defense: false,
    surveillance: false,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 18,
    influence: 'Bureaucracy, Industry',
    influence_qty: 24,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 1,
    description:
      'Você tem uma estante de livros na frente da porta ou passagem secreta, se olhar bem, ainda pode ver a luz em volta da estante, ou então sentir uma brisa da parede a volta.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 2,
    description:
      'A porta se camufla perfeitamente com a parede. O dispositivo que permite abrir esta passagem é difícil de se encontrar.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 3,
    description:
      'As portas são vedadas contra passagem de ar e luz, e além disso pode haver um dispositivo falso.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 4,
    description:
      'Leitores de retina e de impressão digital podem esconder portas secretas, tudo isso combinado com vários dispositivos de abertura verdadeiros e vários outros falsos.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 8,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 5,
    description:
      'Portas e passagens secretas agora foram projetadas para enganar até aparelhos ultra-sônicos, que iriam detectar a passagem como sendo uma parede sólida qualquer. Dispositivos podem possuir sofisticados sistemas de troca de códigos automáticos e os dispositivos de abertura falsos podem esconder armadilhas letais.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 12,
    time_qty: 5,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 6,
    description:
      'As portas possuem técnicas avançadas que identificam todos os membros autorizados a passar por elas, sistemas como identificação biométricas podem ser usados.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Rede de Computadores',
    level: 1,
    description: 'Computadores independentes.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 1,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 2,
    description:
      'Uma rede local com um pequeno servidor e acesso a internet banda larga.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 3,
    description:
      'Uma rede real com servidores dedicados, IP privado/públicos. O nível de segurança é o padrão industrial se equiparando a grandes empresas.',
    defense: false,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 5,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 4,
    description:
      'Um cluster completo de servidores, intranet completamente criptografada, sistema de wireless com criptografia superior ao padrão do governo, sistema de ativação por voz, nível de segurança semelhante às agências de inteligência.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 5,
    description:
      'Sistema básico de Inteligência Artificial. A segurança de seu sistema é o que todo governo gostaria de ter. Este sistema pode controlar quase que sozinho todos os aspectos de seu Refúgio.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 20,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Rede de Computadores',
    level: 6,
    description:
      'Sistema intermediário de Inteligência Artificial. Vários aspectos do Refúgio são controlados completamente pelos computadores. Seus computadores estão conectados a um sistema de identificação biométrica para controle de acesso de pessoas não autorizadas ao Refúgio.',
    defense: true,
    surveillance: true,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 25,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 30,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Segurança Eletrônica',
    level: 1,
    description: 'Conjunto de câmeras preto e branco analógicas.',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 2,
    description:
      'Câmeras infra-vermelhas/noturnas e sensores de movimento, ambos instalados em locais escondidos.',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 3,
    description:
      'Uma pequena rede de lasers e microfones instalados em paredes estratégias que detectam e analisam o som por tipo (humanóides caminhando, pequenos animais quadrúpedes caminhando).',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 6,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 4,
    description:
      'Rede de lasers para análise de dimensão e placas de pressão para análise de peso.',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 5,
    description:
      'Computador que analisa as informações acima e identifica possíveis ameaças.',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 15,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Segurança Eletrônica',
    level: 6,
    description:
      'Computador ligado a rede de computadores interna que analisa os dados e define o tipo de ameaça ou reconhece a pessoa autorizada de acordo com as informações armazenadas em seus banco de dados.',
    defense: false,
    surveillance: true,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 25,
    time_qty: 2,
    time_type: 'months',
  },
];

export default addonsSeed;

/*
pg 24	Sistema de Barcos
pg 27	Túneis Extras
pg 28	Jardim de Fungos
Pg 31	Lago
pg 34	Rede de Mensagens
pg 35	Música Natural
pg 36	Rancho/Fazenda
pg 41	Sopão/Abrigo
pg 42	Logoa da Desova
pg 43	Brechó
pg 44	Lacaios do Warren
pg 46	Sistema Hidraulico
*/
