const addonsSeed = [
  {
    name: 'Aeroporto / Heliporto',
    level: 1,
    description: 'Um heliporto para pequenos helicópteros.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 7,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 2,
    description: 'Um heliporto para helicópteros comerciais.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 11,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 3,
    description:
      'Um aeroporto para aeronaves monomotor e ultra-leves, com pista de terra.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 4,
    description:
      'Um aeroporto com pista de asfalto, suportando pequenos jatinhos, e turbo hélices de transporte de carga.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 22,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 5,
    description:
      'Um aeroporto de respeito, suportando aeronaves comerciais, talvez o maior da região.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 30,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 35,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Aeroporto / Heliporto',
    level: 6,
    description:
      'Um aeroporto internacional, suportando grandes aeronaves, e de carga pesada.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: 'Airport',
    req_influence: 'Transportation x3',
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 40,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 50,
    time_qty: 1,
    time_type: 'years',
  },
  {
    name: 'Animais Defensores',
    level: 1,
    description: '4 animais.',
    defense: 1,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 1,
    influence: 'Bureaucracy, Street',
    influence_qty: 1,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Animais Defensores',
    level: 2,
    description: '8 animais.',
    defense: 2,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 3,
    influence: 'Bureaucracy, Street',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Animais Defensores',
    level: 3,
    description: '12 animais.',
    defense: 3,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 6,
    influence: 'Bureaucracy, Street',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Animais Defensores',
    level: 4,
    description: '16 animais.',
    defense: 4,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 10,
    influence: 'Bureaucracy, Street',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Animais Defensores',
    level: 5,
    description: '32 animais.',
    defense: 5,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 12,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Animais Defensores',
    level: 6,
    description: '48 animais.',
    defense: 6,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other:
      '* Dobro dos Requistos sem Lagoa da Desoava x3 e Rancho/Fazenda x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 20,
    influence: 'Bureaucracy, Street',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 1,
    description: '4 animais.',
    defense: 0,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x1',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 1,
    influence: 'Bureaucracy, Street',
    influence_qty: 1,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Animais Vigilantes',
    level: 2,
    description: '8 animais.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 3,
    influence: 'Bureaucracy, Street',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Animais Vigilantes',
    level: 3,
    description: '12 animais.',
    defense: 0,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x3',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 6,
    influence: 'Bureaucracy, Street',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Animais Vigilantes',
    level: 4,
    description: '16 animais.',
    defense: 0,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x4',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 10,
    influence: 'Bureaucracy, Street',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 5,
    description: '32 animais.',
    defense: 0,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x5',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 12,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Animais Vigilantes',
    level: 6,
    description: '48 animais.',
    defense: 0,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Lagoa da Desoava x6',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 20,
    influence: 'Bureaucracy, Street',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 1,
    description:
      'Você conseguiu esconder pelo menos algumas armadilhas de corda que você tem.',
    defense: 1,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 2,
    description:
      'Você diversificou os tipos de armadilhas, buracos com estacas, grades que caem, baldes de ácido, lanças e flechas que saem de buracos escondidos da parede, uma bola grande que rola por um corredor, e claro, todas ocultas.',
    defense: 2,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 3,
    description:
      'Você conseguiu as mais letais armadilhas (pêndulos com lâminas afiadas, paredes com estacas que se fecham), e claro, colocou um dispositivo para rearmá-las.',
    defense: 3,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Armadilhas',
    level: 4,
    description:
      'Armas estacionárias, muros com estacas de madeira, lança-chamas, grandes quantidades de ácidos e placas de pressão, todos estão no seu arsenal agora.',
    defense: 4,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 9,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 5,
    description:
      'Explosivos e gatilhos remotos foram instalados (você tem o controle remoto para ativar). Em conjunto com a Rede de Computadores você tem uma variada gama de maneiras de matar esperando por um invasor.',
    defense: 5,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 21,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armadilhas',
    level: 6,
    description:
      'Abra o guia do mestre de D&D e veja a tabela de armadilhas, você pode escolher todas.',
    defense: 6,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Craft: Traps, Enigmas, Survival',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 28,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 1,
    description:
      'Armamentos que podem ser disparados em uma única direção controlado por uma pessoa.',
    defense: 1,
    surveillance: 0,
    req_background: 'Resources x1',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 2,
    description:
      'Armamentos montados em uma base giratória mas que ainda devem ser disparados por alguém.',
    defense: 2,
    surveillance: 0,
    req_background: 'Resources x2',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 3,
    description:
      'Controlado por um computador com um sistema básico de análise de ameaças.',
    defense: 3,
    surveillance: 0,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Armamento de Defesa',
    level: 4,
    description:
      'Controlado por um computador com um sistema médio de análise de ameaças.',
    defense: 4,
    surveillance: 0,
    req_background: 'Resources x4',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 9,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 5,
    description:
      'Controlado por um computador com um sistema de Inteligência Artificial Básico.',
    defense: 5,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 21,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Armamento de Defesa',
    level: 6,
    description:
      'Controlado por um computador com um sistema de Inteligência Artificial Intermediário.',
    defense: 6,
    surveillance: 0,
    req_background: 'Resources x6',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Armadilhas x5',
    req_addon_2: 'Rede de Computadores x5',
    req_addon_3: 'Segurança Eletrônica x5',
    ability: 'Enigmas, Survival',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Underworld',
    influence_qty: 28,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Biblioteca',
    level: 1,
    description:
      'Uma pequena sala com uma coleção completa de enciclopédias, alguns clássicos e guias de referência.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 1,
    influence: 'University',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 2,
    description:
      'Algumas salas com um computador, livros de direitos, revistas, e uma coleção de publicações.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 2,
    influence: 'University',
    influence_qty: 8,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 3,
    description:
      'A grande coleção de livros, algumas peças genuínas de arte, e talvez uns dois manuscritos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 3,
    influence: 'University',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 4,
    description:
      'A biblioteca tem pelo menos uma obra-prima, algumas peças genuínas de arte, publicações de conhecimentos perdidos, e mais manuscritos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 4,
    influence: 'University',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 5,
    description:
      'Informações que levariam décadas para serem lidas. Uma inacreditável fonte de conhecimento, a biblioteca possui ao menos uma obra-prima de algum artista famoso e outras tantas obra-primas de artistas não tão conhecidos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 5,
    influence: 'University',
    influence_qty: 22,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Biblioteca',
    level: 6,
    description:
      'A biblioteca possui manuscritos de autores famosos e uma gama de informações sobre todo o mundo afora.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 6,
    influence: 'University',
    influence_qty: 28,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 1,
    description: '2 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 2,
    influence: 'Health, Street, Underworld',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 2,
    description: '4 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 2,
    influence: 'Health, Street, Underworld',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 3,
    description: '8 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 3,
    influence: 'Health, Street, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 4,
    description: '16 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 3,
    influence: 'Health, Street, Underworld',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 5,
    description: '24 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 4,
    influence: 'Health, Street, Underworld',
    influence_qty: 20,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Campo de Caça (Canil)',
    level: 6,
    description: '36 humanos.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Medicine',
    ability_qty: 5,
    influence: 'Health, Street, Underworld',
    influence_qty: 30,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 1,
    description:
      'Você possui um cofre pequeno, com uma senha numérica, escondido atrás de um quadro na parede. Nível de segurança equivalente a um cofre comercial.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 1,
    influence: 'Finance, Industry',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 2,
    description:
      'Você possui um cofre grande, a prova de fogo e com uma fechadura tetra além da senha numérica, no chão de seu escritório. Nível de segurança equivalente a um cofre industrial.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 2,
    influence: 'Finance, Industry',
    influence_qty: 4,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Cofre',
    level: 3,
    description:
      'Seu cofre é uma sala com vários compartimentos, paredes, chão e teto reforçado com várias camadas de metal, hermeticamente fechado e a prova de fogo. O cofre só abre com identificação biométrica. Nível de segurança equivalente a um cofre de banco.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 5,
    influence: 'Finance, Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 4,
    description:
      'Você possui um cofre de dar inveja a qualquer banco, uma sala com vários sub cofres internos, todos muito bem protegidos, além das proteções usuais seu cofre ainda requer um reconhecimento por voz. Nível de segurança equivalente ao de um cofre de cassino.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 10,
    influence: 'Finance, Industry',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 5,
    description:
      'O Tesouro Nacional invejaria seu cofre se o visse. O seu cofre é um cofre dentro de um cofre, duas. É preciso duas chaves e o reconhecimento biométrico e de voz de duas pessoas diferentes, definidas pelos proprietários para abrí-lo. E isto só pode ser feito se ambos estiverem ao mesmo tempo. Nível de segurança equivalente ao de agências do Tesouro Nacional.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 15,
    influence: 'Finance, Industry',
    influence_qty: 20,
    time_qty: 4,
    time_type: 'months',
  },
  {
    name: 'Cofre',
    level: 6,
    description:
      'Se sua casa explodisse, certamente algo ainda estaria de pé e intacto. Nível de Segurança equivalente ao Tesouro Nacional da Suíça.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Segurança Eletrônica x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 25,
    influence: 'Finance, Industry',
    influence_qty: 30,
    time_qty: 8,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 1,
    description:
      'Inscrições mágicas, apitos sobrenaturais, ventos em locais fechados, avisam da presença de algumas criaturas sobrenaturais menores. Pode detectar um carniçal ou alguém com Fé Verdadeira.',
    defense: 0,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x1',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 1,
    influence: 'Occult',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 2,
    description:
      'Quadros que viram os olhos para acompanhar alguém, plantas que murcham, ampulheta que faz a areia subir ao invés de cair, avisam da presença de algumas criaturas sobrenaturais intermediárias. Pode detectar espíritos e alguns fomores.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x2',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 2,
    influence: 'Occult',
    influence_qty: 10,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 3,
    description:
      'Portas que rangem, espelhos que refletem uma imagem distorcida, água que muda de cor, podem ser indícios de que alguma criatura sobrenatural maior está presente no Refúgio. Pode detectar vampiros, lobisomens, fadas. *Ou fantasmas, no caso de Refúgio de membros de clã com Necromancia.',
    defense: 0,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x3',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 3,
    influence: 'Occult',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 4,
    description:
      'Torneiras que se abrem, aparelhos eletrônicos que se ligam sem razão alguma, vozes que ecoam em determinados cômodos avisam da presença de criaturas sobrenaturais superiores. Pode detectar vampiros ofuscados ou em projeção astral, lobisomens na umbra, fantasmas.',
    defense: 0,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x4',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 4,
    influence: 'Occult',
    influence_qty: 30,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 5,
    description:
      'Portas que se fecham e se trancam, barulhos de pessoas correndo por toda parte, gritos estridentes, sangue que escorre da parede, avisam de presenças de criaturas poderosas no Refúgio. Pode detectar presença de demônios ou magos. Podendo inclusive avisar a distância. *Ou Demônios Sebau, no caso do Refúgio de membros clã Setita.',
    defense: 0,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x5',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 5,
    influence: 'Occult',
    influence_qty: 35,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Defesas Sobrenaturais',
    level: 6,
    description:
      'Estátuas que barram a entrada, paredes que falam, água que "caem" do chão para o teto, avisam da presença de criaturas desconhecidas, mas ainda sim, poderosas. Pode detectar a presença de uso de poderes sobrenaturais no local, de criaturas cujo o conhecimento já está muito esquecido, ou mesmo distúrbios que nada tem haver com criaturas, mas está presente no local.',
    defense: 0,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: 'Occult x6',
    req_other: 'Blood Magic',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Occult',
    ability_qty: 6,
    influence: 'Occult',
    influence_qty: 40,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 1,
    description: 'Agradável (Crafts x1).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Design Artístico',
    level: 2,
    description: 'Agradável (Crafts x2).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 7,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Design Artístico',
    level: 3,
    description: 'Impressionante (Crafts x3).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'month',
  },
  {
    name: 'Design Artístico',
    level: 4,
    description: 'Impressionante (Crafts x4).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 14,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 5,
    description: 'Majestoso (Crafts x5).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 19,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Design Artístico',
    level: 6,
    description: 'Majestoso (Crafts x6).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 25,
    time_qty: 1,
    time_type: 'years',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 1,
    description:
      'As paredes são de tijolos, as portas de metal, é necessário algum tempo e uma marreta para derrubar. Alguém com Potência x1 e algum tempo poderia derrubar esta parede fácil.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 2,
    description:
      'Alguém com Potência x2 levaria um bom tempo para derrubar esta parede.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 3,
    description:
      'Alguém com Potência x3 ou uma britadeira levaria algum tempo para romper esta parede.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 15,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 4,
    description:
      'Alguém com Potência x4 e algum tempo ou uma pequena quantidade de explosivos poderiam derrubar esta parede.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 20,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 5,
    description:
      'Alguém com Potência x5 e algum tempo ou uma média quantidade de explosivos poderiam derrubar esta parede.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 30,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Estruturas Reforçadas',
    level: 6,
    description:
      'As paredes apenas vibram em um grande terremoto. Materiais feitos para resistir a terremotos foram utilizados na construção destas paredes para prevenir que sejam derrubadas.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 40,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Labirinto',
    level: 1,
    description:
      'Dois corredores, se você pegar o da esquerda encontrará o caminho.',
    defense: 1,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Túneis Extras x1',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 2,
    description: 'Um único piso, mas um desafio menor.',
    defense: 2,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Túneis Extras x2',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 3,
    description:
      'Dois ou três pisos, ou algumas centenas de metros quadrados, um verdadeiro desafio.',
    defense: 3,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Túneis Extras x3',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 8,
    time_qty: 3,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 4,
    description:
      'Muitos pisos (4-6), ou alguns quilômetros quadrados, e muito complexo, algumas paredes escondem alavancas que abrem portas secretas. Uma vez vi um minotauro andando por aqui.',
    defense: 4,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: '* Dobro dos Requistos sem Túneis Extras x4',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 12,
    time_qty: 4,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 5,
    description:
      'Complexo subterrâneo multifacetado. Algumas das paredes de posição automaticamente. Muitas vezes, alguns movimentos fazem o labirinto se fecham completamente, permitindo a saída apenas se conhecer alguma porta secreta.',
    defense: 5,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 16,
    time_qty: 5,
    time_type: 'months',
  },
  {
    name: 'Labirinto',
    level: 6,
    description:
      'O labirinto se estende para baixo, sumindo cada vez mais na escuridão. Os que ficam presos dentro dele, descem cada vez mais, a maioria nunca volta.',
    defense: 6,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 24,
    time_qty: 6,
    time_type: 'months',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 1,
    description:
      'O laboratório possui ferramentas o suficiente para realizar algumas experiências básicas.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x1',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 1,
    influence: 'University',
    influence_qty: 3,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 2,
    description:
      'O laboratório possui recursos para realizar pesquisas novas e expandir o conhecimento em várias áreas. Mais de um cientista pode trabalhar ao mesmo tempo neste local.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x2',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 2,
    influence: 'University',
    influence_qty: 6,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 3,
    description:
      'O laboratório tem salas e equipamento para suportar vários cientistas e potencialmente grandes cientistas. Seus recursos podem produzir trabalhos originais e de grande influência.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 3,
    influence: 'University',
    influence_qty: 9,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 4,
    description:
      'O laboratório tem equipamentos únicos para suportar uma figura significativa da área científica. Trabalhos verdadeiramente originais podem ser produzidos neste departamento. Este laboratório pode publicar regularmente teses científicas.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x4',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 4,
    influence: 'University',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 5,
    description:
      'Este laboratório pode competir com grandes laboratórios de pesquisa. Tudo que um laboratório precisa, ele tem. Ele pode produzir patentes o suficiente para ter seu mérito reconhecido mundialmente, mas isso não quer dizer que ele divulgue isso para o mundo mortal.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x5',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 5,
    influence: 'University',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Laboratório de Pesquisas',
    level: 6,
    description:
      'Este laboratório é uma referência para seu campo de estudo. Boatos de seu trabalho correm pelos grandes círculos de seu campo de estudo.',
    defense: 0,
    surveillance: 0,
    req_background: 'Resources x6',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Biblioteca x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics',
    ability_qty: 6,
    influence: 'University',
    influence_qty: 18,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Oficina Mecânica',
    level: 1,
    description:
      'Uma oficina humilde, com um pequeno set de ferramentas, você pode trocar uma fechadura ou pregar algumas tábuas aqui.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 2,
    description:
      'Um conjunto respeitável de ferramenta, assim como uma mesa apropriada, você pode consertar equipamentos e/ou Add-ons de até nível 2.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry',
    influence_qty: 8,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 3,
    description:
      'Algumas ferramentas incomuns está presente no local, como serra tico-tico entre outras, pode consertar equipamentos de até nível 3.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry',
    influence_qty: 12,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 4,
    description:
      'Uma grande gama de ferramentas, algumas restrita a construção civil, pode se encontrar bombas de ar, britadeira, torqueadeira, tudo a disposição, pode se reparar equipamentos de até nível 4.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 8,
    influence: 'Bureaucracy, Industry',
    influence_qty: 16,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 5,
    description:
      'Tudo que precisa numa oficina tem ali, um escavadeira está estacionada no canto, cabos e vigas de aço no teto permite o transporte fácil de equipamento pesado, pode consertar equipamentos de até nível 5.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 12,
    influence: 'Bureaucracy, Industry',
    influence_qty: 20,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Oficina Mecânica',
    level: 6,
    description:
      'Você tem ferramentas modificadas para cada equipamento em seu refúgio. Pode arrumar qualquer coisa de nível 6 ou inferior.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Repair',
    ability_qty: 18,
    influence: 'Bureaucracy, Industry',
    influence_qty: 24,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 1,
    description:
      'Você tem uma estante de livros na frente da porta ou passagem secreta, se olhar bem, ainda pode ver a luz em volta da estante, ou então sentir uma brisa da parede a volta.',
    defense: 0,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 2,
    description:
      'A porta se camufla perfeitamente com a parede. O dispositivo que permite abrir esta passagem é difícil de se encontrar.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 3,
    description:
      'As portas são vedadas contra passagem de ar e luz, e além disso pode haver um dispositivo falso.',
    defense: 0,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 4,
    description:
      'Leitores de retina e de impressão digital podem esconder portas secretas, tudo isso combinado com vários dispositivos de abertura verdadeiros e vários outros falsos.',
    defense: 0,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 8,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 5,
    description:
      'Portas e passagens secretas agora foram projetadas para enganar até aparelhos ultra-sônicos, que iriam detectar a passagem como sendo uma parede sólida qualquer. Dispositivos podem possuir sofisticados sistemas de troca de códigos automáticos e os dispositivos de abertura falsos podem esconder armadilhas letais.',
    defense: 0,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 12,
    time_qty: 5,
    time_type: 'weeks',
  },
  {
    name: 'Porta/Passagem Secretas',
    level: 6,
    description:
      'As portas possuem técnicas avançadas que identificam todos os membros autorizados a passar por elas, sistemas como identificação biométricas podem ser usados.',
    defense: 0,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Enigmas',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 16,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Rede de Computadores',
    level: 1,
    description: 'Computadores independentes.',
    defense: 0,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 1,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 2,
    description:
      'Uma rede local com um pequeno servidor e acesso a internet banda larga.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 3,
    description:
      'Uma rede real com servidores dedicados, IP privado/públicos. O nível de segurança é o padrão industrial se equiparando a grandes empresas.',
    defense: 0,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 5,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 4,
    description:
      'Um cluster completo de servidores, intranet completamente criptografada, sistema de wireless com criptografia superior ao padrão do governo, sistema de ativação por voz, nível de segurança semelhante às agências de inteligência.',
    defense: 2,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Computadores',
    level: 5,
    description:
      'Sistema básico de Inteligência Artificial. A segurança de seu sistema é o que todo governo gostaria de ter. Este sistema pode controlar quase que sozinho todos os aspectos de seu Refúgio.',
    defense: 2,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 20,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Rede de Computadores',
    level: 6,
    description:
      'Sistema intermediário de Inteligência Artificial. Vários aspectos do Refúgio são controlados completamente pelos computadores. Seus computadores estão conectados a um sistema de identificação biométrica para controle de acesso de pessoas não autorizadas ao Refúgio.',
    defense: 2,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Computer',
    ability_qty: 25,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 30,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Segurança Eletrônica',
    level: 1,
    description: 'Conjunto de câmeras preto e branco analógicas.',
    defense: 0,
    surveillance: 1,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 2,
    description:
      'Câmeras infra-vermelhas/noturnas e sensores de movimento, ambos instalados em locais escondidos.',
    defense: 0,
    surveillance: 2,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 3,
    description:
      'Uma pequena rede de lasers e microfones instalados em paredes estratégias que detectam e analisam o som por tipo (humanóides caminhando, pequenos animais quadrúpedes caminhando).',
    defense: 0,
    surveillance: 3,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 6,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 4,
    description:
      'Rede de lasers para análise de dimensão e placas de pressão para análise de peso.',
    defense: 0,
    surveillance: 4,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 10,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 10,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Segurança Eletrônica',
    level: 5,
    description:
      'Computador que analisa as informações acima e identifica possíveis ameaças.',
    defense: 0,
    surveillance: 5,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 15,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 15,
    time_qty: 1,
    time_type: 'months',
  },
  {
    name: 'Segurança Eletrônica',
    level: 6,
    description:
      'Computador ligado a rede de computadores interna que analisa os dados e define o tipo de ameaça ou reconhece a pessoa autorizada de acordo com as informações armazenadas em seus banco de dados.',
    defense: 0,
    surveillance: 6,
    req_background: 'Resources x3',
    req_merit: null,
    req_influence: null,
    req_other: null,
    req_addon_1: 'Rede de Computadores x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Security',
    ability_qty: 20,
    influence: 'Bureaucracy, Industry, Police, University',
    influence_qty: 25,
    time_qty: 2,
    time_type: 'months',
  },
  {
    name: 'Sistema de Barcos',
    level: 1,
    description:
      'Grande o suficiente para um caiaque, uma canoa ou um bote de borracha.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Sistema de Barcos',
    level: 2,
    description:
      'Grande o suficiente para um barco a remo, uma jangada grande, ou um barquinho a motor.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Sistema de Barcos',
    level: 3,
    description:
      'Grende o suficiente para uma gondola pequena (2 pessoas) ou um jet ski.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 10,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Sistema de Barcos',
    level: 4,
    description:
      'Grande o suficiente para uma gondola média (4 pessoas) ou um barco pequeno a motor.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 10,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Sistema de Barcos',
    level: 5,
    description:
      'Grande o suficiente para uma gondola grande (6 pessoas) ou um barco médio a motor.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 20,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Sistema de Barcos',
    level: 6,
    description:
      'Grande o suficiente para um grande banco a motor (talvez até uma arca).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Túneis Extras x2',
    req_addon_2: 'Sistema Hídrico x4',
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 6,
    influence: 'Bureaucracy, Industry, Transportation',
    influence_qty: 20,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 1,
    description: 'Aproximadamente 1,5 km de túneis extras.',
    defense: 0,
    surveillance: 1,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 2,
    description: 'Aproximadamente 3 km de túneis extras.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 10,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 3,
    description: 'Aproximadamente 6,5 km de túneis extras.',
    defense: 0,
    surveillance: 3,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 15,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 4,
    description: 'Aproximadamente 13 km de túneis extras.',
    defense: 0,
    surveillance: 4,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 20,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 5,
    description: 'Aproximadamente 26 km de túneis extras.',
    defense: 0,
    surveillance: 5,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 25,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Túneis Extras',
    level: 6,
    description: 'Aproximadamente 36 km de túneis extras.',
    defense: 0,
    surveillance: 6,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Lacaios do Warren x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 30,
    time_qty: 6,
    time_type: 'weeks',
  },

  {
    name: 'Sistema Hídrico',
    level: 1,
    description:
      'A água chega onde você quiser quando chove, e as coisas ficam geralmente seca no warren. O cheiro de mofo é apenas ligeiramente aparente.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry',
    influence_qty: 3,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Sistema Hídrico',
    level: 2,
    description:
      'A água chega onde você quiser quando chove e as coisas ficam secas no warren o tempo todo.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry',
    influence_qty: 4,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Sistema Hídrico',
    level: 3,
    description:
      'Você tem um suprimento de água para três meses e para uma pequena Lagoa de Desova, suprir animais e quaisuqer mortais abaixo do solo. Agora é seguro construir a maioria doa addons (níveis 1 e 2).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry',
    influence_qty: 5,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Sistema Hídrico',
    level: 4,
    description:
      'Você tem um abastecimento razoável de água subterrânea, permitindo a contrução de addons maiores (níveis 3 e 4).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry',
    influence_qty: 6,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Sistema Hídrico',
    level: 5,
    description:
      'Você tem um suprimento confiável de água subterrânea, permitindo suprir as necessidades de todas as construções (nível 5).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry',
    influence_qty: 7,
    time_qty: 5,
    time_type: 'weeks',
  },
  {
    name: 'Sistema Hídrico',
    level: 6,
    description:
      'Você naturalmente enche as Lagoas de Desova com água desviada, pode montar armadilhas e usar a água a vontade. Este sistema também suporta corpos maiores de água como (Lago), e garante que qualquer transporte aquático tenha como funcionar (Sistema de Barcos).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture, Science: Engineering',
    ability_qty: 6,
    influence: 'Bureaucracy, Industry',
    influence_qty: 8,
    time_qty: 6,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 1,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 1,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x1',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 2,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 1,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 2,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 2,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x2',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 4,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 2,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 3,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 3,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x3',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 6,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 3,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 4,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 4,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x4',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 8,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 4,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 5,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 5,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 10,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 6,
    time_qty: 5,
    time_type: 'weeks',
  },
  {
    name: 'Jardim de Fungos',
    level: 6,
    description: 'Este é um jardim bem imaturo. Pode ser pisado facilmente.',
    defense: 6,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x6',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Biology, Science: Chemistry',
    ability_qty: 15,
    influence: 'Bureaucracy, Health, University',
    influence_qty: 8,
    time_qty: 8,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 1,
    description:
      'Um pequeno lago, mais parecido com uma lagoa, com cerca de meio acre de tamanho.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Próximo a um curso de água',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 1,
    influence: 'Bureaucracy',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 2,
    description:
      'Um pequeno lago com pequenos peixes, com cerca de um acre de tamanho.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Próximo a um curso de água',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 2,
    influence: 'Bureaucracy',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 3,
    description:
      'Um lago com vários peixes, um deles grande inclusive, medindo aproximadamente 4 hectares.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 3,
    influence: 'Bureaucracy',
    influence_qty: 15,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 4,
    description:
      'Um lago com cerca de 8 hectares de tamanho, com uma ilha e muitos peixes.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 4,
    influence: 'Bureaucracy',
    influence_qty: 20,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 5,
    description:
      'Um grande lago com cerca de 16 hectares de tamanho, com uma ou duas ilhas e diversos peixes grandes.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy',
    influence_qty: 25,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Lago',
    level: 6,
    description:
      'Um lago enorme com cerca de 32 hectares de tamanho, com uma grande ilha e um ecossistema completo.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: 'Sistema Hídrico x5',
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Science: Engineering',
    ability_qty: 6,
    influence: 'Bureaucracy',
    influence_qty: 30,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 1,
    description:
      'Você tem alguns ratos mensageiros e um ou dois tubos pneumáticos, e em alguns casos você bate nos tubos em código Morse para se comunicar.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 1,
    influence: 'Bureaucracy, Industry',
    influence_qty: 5,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 2,
    description:
      'Você conectou o Warren com um sistema de fios de telefone e usa como um sistema de intercomunicação.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 2,
    influence: 'Bureaucracy, Industry',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 3,
    description:
      'Você está usando um sistem de comunicação por walkie-talkies sem fio. Alguns repetidores foram instalados para que a comunicação por rádio funcione no subsolo.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 3,
    influence: 'Bureaucracy, Industry',
    influence_qty: 15,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 4,
    description:
      'Você conectou seu sistema de comunicação ao sistema de computadores e pode rastrear siais em todo os Warrens.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 4,
    influence: 'Bureaucracy, Industry',
    influence_qty: 20,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 5,
    description:
      'Você está equipado com videofones portáteis conectados ao sistema de computadores.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 5,
    influence: 'Bureaucracy, Industry',
    influence_qty: 30,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Rede de Mensagens',
    level: 6,
    description:
      'Um sistema sem fio está disponpivel com conexão direta à Rede de Computadores e pode se comunicar em todos os canais.',
    defense: 0,
    surveillance: 2,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Academics, Science: Engineering',
    ability_qty: 6,
    influence: 'Bureaucracy, Industry',
    influence_qty: 45,
    time_qty: 4,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 1,
    description: 'Duas fontes de som natural combinando em um ritmo.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 1,
    influence: 'Industry',
    influence_qty: 2,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 2,
    description:
      'Três fontes de som natural combinando em um ritmo e melodia (Performance x2).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 2,
    influence: 'Industry',
    influence_qty: 4,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 3,
    description:
      'Quatro fontes de som natural combinando em um ritmo e melodia, mudando a melodia em uma transição lenta ao longo do tempo (Performance x3).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 3,
    influence: 'Industry',
    influence_qty: 6,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 4,
    description:
      'Uma sinfonia de fontes naturais de som combinando em ritmo e melodia, variando altura e tom com as várias melodias que transitam naturalmente (Performance x4).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 4,
    influence: 'Industry',
    influence_qty: 8,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 5,
    description:
      'Uma sinfonia de fontes naturais de som combinando em ritmo e melodia, variando em altura e tom conforme ocorre a magistral transição das melodias. O produto final é semelhante a assistir ao vivo à uma orquestra de sons naturais (Performance x5).',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 5,
    influence: 'Industry',
    influence_qty: 12,
    time_qty: 3,
    time_type: 'weeks',
  },
  {
    name: 'Música Natural',
    level: 6,
    description:
      'Uma sinfonia de fontes naturais em vários níveis que reverbera por todo o Warren, e não apenas na câmera acústica.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Crafts: Architecture',
    ability_qty: 6,
    influence: 'Industry',
    influence_qty: 16,
    time_qty: 4,
    time_type: 'weeks',
  },

  {
    name: 'Rancho/Fazenda',
    level: 1,
    description:
      'Você tem algumas pequenas cavernas ou campos de cogumelos e uma pequena fazenda que atende às necessidades de uma pequena Lagoa da Desova ou de um Laboratório de Pesquisas. Os animais não são muito bem tratados e os Canis básicos têm um pouco de dificuldade em não passar fome.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 2,
    influence: 'Bureaucracy, Street',
    influence_qty: 3,
    time_qty: 3,
    time_type: 'days',
  },
  {
    name: 'Rancho/Fazenda',
    level: 2,
    description:
      'A estrutura estabelecida é grande o suficiente para fornecer uma quantidade média de comida ou baías hidropônicas simples. Os Canis e os Animais são alimentados com básico necessário para se manterem saudáveis.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 4,
    influence: 'Bureaucracy, Street',
    influence_qty: 6,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rancho/Fazenda',
    level: 3,
    description:
      'Esta é uma fazenda grande, com muitos trabalhadores. Ela produz comida especializados para o Warren. Você pode alimentar uma grande Lagoa da Desova. Canis e Animais nunca passam fome.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 6,
    influence: 'Bureaucracy, Street',
    influence_qty: 10,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rancho/Fazenda',
    level: 4,
    description:
      'Esta fazenda é tão sofisticada quanto a maioria das fazendas modernas, produzindo diversas amenidades e alimentos. Ela pode sustentar todas as necessidades de um Warren se vinculado a uma Lagoa da Desova.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 10,
    influence: 'Bureaucracy, Street',
    influence_qty: 14,
    time_qty: 1,
    time_type: 'weeks',
  },
  {
    name: 'Rancho/Fazenda',
    level: 5,
    description:
      'Você pode alimentar várias Lagoas da Desova de grande porte, além de manter todas as necessidades de alimento.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 19,
    time_qty: 2,
    time_type: 'weeks',
  },
  {
    name: 'Rancho/Fazenda',
    level: 6,
    description:
      'O Rancho/Fazenda se especializou em suas Lagoas da Desova e seus Animais podem alcançar o próximo estágio em mutações genética.',
    defense: 0,
    surveillance: 0,
    req_background: null,
    req_merit: null,
    req_influence: null,
    req_other: 'Warrens Nosferatu',
    req_addon_1: null,
    req_addon_2: null,
    req_addon_3: null,
    ability: 'Animal Ken',
    ability_qty: 15,
    influence: 'Bureaucracy, Street',
    influence_qty: 24,
    time_qty: 3,
    time_type: 'weeks',
  },
];

export default addonsSeed;

/*
pg 41	Sopão/Abrigo
pg 42	Logoa da Desova
pg 43	Brechó
pg 44	Lacaios do Warren
*/
